ALTER TABLE LIST_TAG
DROP CONSTRAINT PFK_PL_NO;

ALTER TABLE LIST_TAG 
ADD CONSTRAINT PFK_PL_NO FOREIGN KEY (PL_NO) REFERENCES PLACE_LIST(PL_NO) ON DELETE CASCADE;

ALTER TABLE MY_TAG
DROP CONSTRAINT PFK_MY_NO;

ALTER TABLE MY_TAG 
ADD CONSTRAINT PFK_MY_NO FOREIGN KEY (MY_NO) REFERENCES MY_LIST(MY_NO) ON DELETE CASCADE;

INSERT INTO MY_LIST VALUES(SEQ_MY_NO.NEXTVAL, '카츠오모이', '서울특별시 강동구', '02-222-7778', 5, 'C3', 'N');
INSERT INTO MY_LIST VALUES(SEQ_MY_NO.NEXTVAL, '서울족발', '서울특별시 구로구', '02-212-7668', 4, 'C1', 'Y');

DELETE my_list
WHERE my_name = '카츠오모이';

SELECT *
FROM MY_LIST ml;

UPDATE MY_LIST SET
MY_NAME = '입이가짬뽕' ,
MY_ADDRESS = '서초구' 
WHERE MY_NAME = '이비가짬뽕';

SELECT *
FROM MY_LIST ml 


SELECT 
	ROWNUM,
	A.PL_NAME ,
	A.PL_ADDRESS ,
	A.PL_TEL ,
	A.SCORE ,
	A.PL_RESERVE ,
	A.PL_CATECODE,
	CATE.CATEGORY_NAME,
	TAG.*
FROM (
		SELECT 
			A.PL_NO ,
			LISTAGG(C.TAG_CODE ,',') WITHIN GROUP (ORDER BY A.PL_NO) tagcode,
			LISTAGG(C.TAG_NAME,',') WITHIN GROUP (ORDER BY A.PL_NO) 태그
		FROM PLACE_LIST A
		JOIN LIST_TAG B ON A.PL_NO = B.PL_NO 
		JOIN TAG C ON B.TAG_CODE = C.TAG_CODE
		GROUP BY A.PL_NO
	) TAG
JOIN PLACE_LIST A ON TAG.PL_NO = A.PL_NO
JOIN CATEGORY CATE ON A.PL_CATECODE = CATE.CATEGORY_CODE;